### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by dev-chenxing** [dev-chenxing/farming-game#1]
- [ ] 背篓
- [ ] 小茅屋
- [ ] 小河边：鱼篓，半天小半碗小鱼虾
- [ ] 路边摘点野菜
- [ ] 一路上遇到好几个早起的村民，大家都急着下地干活，点头就算是打了招呼
- [ ] 鱼虾粥：半碗米，小半碗鱼虾，野菜一把
- [ ] 大片的地因无人耕种而长期长满了荒草
- [ ] 玉米地在山崖上，上山下山破费时间
    - [ ] 还要预防狐狸、黄鼠狼来偷吃

**Comment by dev-chenxing** [comment]
- [ ] 手指翻飞，几下就编织出来一只鱼篓
- [ ] 河水清澈见底，河底铺满了各式的鹅卵石，河边长着齐腰深的水草
- [ ] 找了个合适的地方，挨个放下了三个鱼篓
